### ISSUE TITLE
Inconsistent method names

### ISSUE THREAD

**Issue by samuelwilliams** [rlanvin/php-ip#20]
https://github.com/rlanvin/php-ip/blob/210b8fb956bdba4c971650626cfda84883321ec5/src/IPBlock.php#L311-L331

`getSubblocks()` should be renamed to `getSubBlocks()` to make it properly camel-case. Additionally, `getSuper()` should be renamed to `getSuperBlock()` so that it is consistent with the `getSubBlocks()`

**Comment by rlanvin** [comment]
Agreed, however the old method must be kept. It will just calls the new method and trigger a E_DEPRECATED error. That will make the upgrade easier for users of this lib.
