### ISSUE TITLE
Move iterator methods into own object

### ISSUE THREAD

**Issue by samuelwilliams** [rlanvin/php-ip#23]
I think it would be cleaner to move the iterator methods in `IPBlock` into their own object (say, `SubnetIterator`) and have `IPBlock` implement `\IteratorAggregate`

https://github.com/rlanvin/php-ip/blob/5c636122419ea2284d306c06482d42aace71f19b/src/IPBlock.php#L497-L524

**Comment by rlanvin** [comment]
Would it be even cleaner to use a generator instead?
