### ISSUE TITLE
128.0.0.0/16 does not appear to be an IPv4 or IPv6 block

### ISSUE THREAD

**Issue by f0o** [rlanvin/php-ip#4]
Hi,

I just downloaded the bundled `ip.lib.php` and when I try the example for IP-Blocks from the wiki I get:
```
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message '128.0.0.0/16 does not appear to be an IPv4 or IPv6 block' in test.php:620
Stack trace:
#0 test.php(1095): IPBlock::create('128.0.0.0/16')
#1 {main}
  thrown in test.php on line 620
```

here the script:
```php
<?php
// ...
// ip.lib.php contents
// ...

$block = IPBlock::create('128.0.0.0/16'); // IPv4Block
```

PHP 5.6 on upstream Debian Jessie

**Comment by f0o** [comment]
Closing this issue, the bundled ip.lib.php is simply outdated, I bundled it myself with the src/*/* files and it works like a charm.

**Comment by rlanvin** [comment]
Thanks for letting me know, I updated the bundle file on the repository.
