### ISSUE TITLE
Issues when using composer in combination with PHP5.6

### ISSUE THREAD

**Issue by Jerommeke4** [rlanvin/php-ip#5]
We found out that using PHP5.6 requires us to use version 1.0.1 of the library since this contains a fix for the GMP library that is now build into PHP instead of using the extension. However, installing through composer will require you to install the php-gmp extension which is no longer available. Making installing through composer not working for us. 

Are you planning on branching a PHP5.6 and higher version of the library? Or otherwise shouldn't the gmp extension to not be required in the library but just a recommended extension?

**Comment by rlanvin** [comment]
May I ask what is the error you are having, and what is your platform? I have PHP 5.6 and I don't have this problem. Travis CI also works fine with 5.6 and show error during `composer install` phase, so I'm a bit surprised.

**Comment by rlanvin** [comment]
@Jerommeke4 Anything new?

**Comment by rlanvin** [comment]
I'm closing this for now. If you can provide more details on how to reproduce your problem I'll reopen it.
