### ISSUE TITLE
How to Implement this on project?

### ISSUE THREAD

**Issue by Eggotron** [rlanvin/php-ip#59]
Maybe is an stupid question but I can't figure out how to use this on my project.

I've tried with `require_once(base_path() . '/vendor/rlanvin/php-ip/src/IPv4Block.php'); `or using directly the Model on my Controller but cant make it work.

Any tips would be appreciated :)

**Comment by samuelwilliams** [comment]
Hi @Eggotron 

You need to import the Composer autoloader which is `vendor/autoload.php`

I hope this helps!
