### ISSUE TITLE
Deprecate IP::create()

### ISSUE THREAD

**Issue by samuelwilliams** [rlanvin/php-ip#65]
There are too many instances where `IP::create()` will produce undesired results. Basically any 4 byte string will return an undesired IPv4 address. I don't think it is safe for the IP library to be doing the type juggling; the onus should be put on the implementing app to decide what version an IP address takes.

I suggest the following:
1. Deprecate `IP::create()`
2. Refactor `IPBlock::containsIP()` so that it does not rely on the method.
3. In documentation, encourage developers to use `IPv4` or `IPv6` explicitly.
4. If the method's functionality is still seen as highly desirable - change it's name to `IP::guess()` which better conveys the risk of its implementation.

**Comment by rlanvin** [comment]
Hi @samuelwilliams, I tend to agree, but did you check my PR #64 (WIP v3)? Point 2 in already done for example, so I wonder if you could maybe provide some examples for undesired results with the WIP v3.

**Comment by rlanvin** [comment]
I release v3.0.0-rc1 today, and updated the doc to reflect your suggestion 3. Happy to get some feedback. See: https://github.com/rlanvin/php-ip/releases/tag/v3.0.0-rc1 and https://github.com/rlanvin/php-ip/wiki
