### ISSUE TITLE
IPv4Block::getPrivateBlocks() and IPv6Block::getPrivateBlocks() returns to much entries

### ISSUE THREAD

**Issue by bkuebler** [rlanvin/php-ip#67]
With the both new methods in version > 3.0.0 i expected to just get the private IP blocks not all reserved blocks. It would be a better solution to just give the "private blocks" back with this method instead of reserved blocks.

1. Remove blocks which are not defined as "private networks" or "private internets"
2. Add an additional method ::getReservedBlocks() to get the full list

**Use case**

If i would filter IP Blocks which should not be in Private Networks they are also possible to be in any other reserved IP Space.

**Comment by rlanvin** [comment]
That's a good point, thanks for raising it. I like your suggestion, I'll update the version 3 before final release.

**Comment by bkuebler** [comment]
I already have a patch if you like i could add a pull request

**Comment by rlanvin** [comment]
Yes sure, please create a PR!

**Comment by rlanvin** [comment]
Thanks for the PR, it's merged. With your PR, I learned more about the IANA Special-Purpose Address Registry. Now I'm wondering if it wouldn't be even better to implement this registry inside the lib. With that, I mean, for example, adding methods such as:

- `::getName()`
- `::getAllocationDate()`
- `::getTerminationDate()`
- `::getRFC()`
- `::getSource()`
- `::getDestination()`
- `::getForwardable()`
- `::getGloballyReachable()`
- `::getReservedByProtocol()`

and/or method search the registry for blocks that matches certains conditions, e.g. "forwadable=true and globally reachable=false" (`getPrivateBlock()` and `getReservedBlocks()` could then just use this method).

What do you think?

**Comment by bkuebler** [comment]
I'm not against this idea, but the use-case is very small I think. Maybe add this as extra issue for idea or improvement.
