### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by acelaya** [rlanvin/php-ip#72]
Hi!

I have been using v3.0.0-rc2 for some time and it works quite fine with PHP 8.0.

However, I have recently updated to PHP 8.1 and this library throws the next deprecation warnings.

```
Deprecated: Return type of PhpIP\IPBlock::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/shlink/vendor/rlanvin/php-ip/src/IPBlock.php on line 607

Deprecated: Return type of PhpIP\IPBlock::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/shlink/vendor/rlanvin/php-ip/src/IPBlock.php on line 617
```

They don't seem super hard to fix, so I can provide a PR if you want. Would you be open for it?

**Comment by acelaya** [comment]
I don't think BC needs to be broken to fixt those warnings. In the wors case scenario, adding the `#[\ReturnTypeWillChange]` attributes would be a short-term fix for the warning, and it would be treated as a comment for older PHP versions.

**Comment by rlanvin** [comment]
Since v3 hasn't been fully released yet, that might actually be a good time to break BC and bump to 7.1 minimum. I also see that PHP 7.0 is EOL since January 2019 so even folks lagging way behind should have migrated to at least 7.1 now.
So TL;DR: I'm ok for bumping to 7.1. Please add a BC break warning in the changelog file, as part of your PR.

**Comment by acelaya** [comment]
Perfect!

**Comment by acelaya** [comment]
There we go https://github.com/rlanvin/php-ip/pull/73

Not sure if that's the kind of CHANGELOG format you usually use. I followed "keep-a-changelog" one and added an "Unreleased" block.

**Comment by rlanvin** [comment]
Merged, thank you! I'll try to release the v3 soon.

**Comment by acelaya** [comment]
Thank you!

**Comment by acelaya** [comment]
Hey @rlanvin 

I hate to be that person, but do you think you will be releasing v3 soon? 😅 

If the answer is "no", that's perfectly fine. It's just that it's the very last dependency preventing me from supporting PHP 8.1 in some project, and I want to be able to plan accordingly.

And again, sorry again for being that person.

**Comment by rlanvin** [comment]
Hello @acelaya,
No worries at all. I released v3 yesterday. I'm very sorry for the late answer, for some reason I didn't get a notification for this ticket and I got carried away by work and other projects and forgot about this... Hope this isn't too late for you!
