### ISSUE TITLE
How to use this library in PHP Laravel ?

### ISSUE THREAD

**Issue by jainsiddharth21** [rlanvin/php-ip#76]
Hi @rlanvin, could you please guide me how to use this library in Laravel to check whether the IP is in Block range or not.
I'm looking for combinations like:-
1. IP in block
2. Smaller Block in larger Block
3. Also check the vice versa conditions.

Thanks in advance.

**Comment by rlanvin** [comment]
Hello, I think whether you are using Laravel or another framework shouldn't matter. You should be able to find the answer to your questions in the documentation here: https://github.com/rlanvin/php-ip/wiki#blocks-networks

If you have a particular problem or bug with this library specifically on Laravel please describe it and how to reproduce it and I'll have a look.
