### ISSUE TITLE
Drop support for PHP <5.6?

### ISSUE THREAD

**Issue by rlanvin** [rlanvin/php-ip#8]
The codebase of this library is very old - it was originally coded for a project using PHP 5.2. Therefore the lib doesn't use namespace, and as some quirks to work around the lack of late static binding.

Does anybody still need support for PHP < 5.6? Older version 5.2 to 5.5 have reached end of life and are not supported anymore by PHP (see http://php.net/supported-versions.php).

If not, then we can probably work on a version 2 with an "IP" namespace and clean up the object model a bit.

**Comment by haegar** [comment]
I am currently using it with PHP 5.4 (Debian Wheezy) and 5.6 (Debian Jessie) - but all code that gets more than bugfixes is using 5.6 and will move to PHP 7 after Debian Stretch gets out.

So fine with me for requiring 5.6

**Comment by rlanvin** [comment]
@haegar Alright. Well the branch 1.* will still be available for Debian oldstable, so I guess this is ok. I'm curious, may I ask in what project/package you are using this lib?

> But what I really like is not requiring composer or another autoloader conflicting with other stuff.

I agree. I don't want to require composer in any way, so I always keep an alternate way of installing the lib.

**Comment by johanfleury** [comment]
I think you should consider dropping support for any version < 7.0 as they are not supported anymore (see [PHP Supported Versions](https://secure.php.net/supported-versions.php)).

You might wan to keep support for PHP 7.0 as it is still used/maintained on Debian 9 (Stretch) and related.

**Comment by samuelwilliams** [comment]
See PR#11 which is a full re-work of the project. It will require minimal changes to dependent code-bases. I would like to submit this a v2.0 release candidate.

**Comment by rlanvin** [comment]
@samuelwilliams I'm leaving some comments here. I think your work is going to the right direction, and I wanted to thank you for your effort. Please review my comments and update your PR accordingly and I'll merge them.

Now how far do you want to go with this? I think at this point in time it would make sense to drop support for anything < 7.0 like @johanfleury suggested, and add things like type hinting for example.

**Comment by samuelwilliams** [comment]
I think we should.  I've been deliberate in keeping things 5.3 compatible,  but a major release is probably due. Maybe we should have a 2.0 branch that we can merge into.

**Comment by rlanvin** [comment]
@samuelwilliams Yes let's do that and use PHP 7.0 as a minimum required version.

**Comment by samuelwilliams** [comment]
Short form or long form arrays? (I think short form)

**Comment by rlanvin** [comment]
@samuelwilliams Short form is fine.

**Comment by samuelwilliams** [comment]
I think with PR #46 (and maybe #47), the project will be ready for v2.0.

**Comment by samuelwilliams** [comment]
@rlanvin Do you think the codebase is ready for v2.0?

**Comment by rlanvin** [comment]
Yes I do! I'm still waiting for feedback about #47 but I can prepare a 2.0.0-rc1 release. I'll try to do that this week-end.

**Comment by rlanvin** [comment]
@samuelwilliams version 2.0.0-rc1 has been release. I'll test it in some projects. In a couple of weeks, if there is no negative feedback I'll release the final version. Thank you for all your contributions, it wouldn't have been possible without you!

**Comment by samuelwilliams** [comment]
Thanks for giving me the opportunity to contribute to a really valuable library!

**Comment by rlanvin** [comment]
Closing this issue as v2.0.0 as been released.
